### ISSUE TITLE
TnT Shiny render functions

### ISSUE THREAD

**Issue by UmaSangumathi** [Marlin-Na/TnT#2]
Hi Jialin Ma... Nice work, I used your TnT R package to create a genome browser in Rstudio and it works great. 
When I try to render it in Shiny based on the example you provided - https://marlin-na.github.io/TnT/reference/TnT-shiny.html ; the error is "could not find function TnTOutput". I couldn't find TnTOuput and renderTnT functions in the installed TnT library (devtools::install_github("marlin-na/TnT")). 
Please let me know the link of the package with these functions. Thanks so much. 
-Uma

**Comment by Marlin-Na** [comment]
Thanks for trying the package, I have just pushed a new version to github, with `renderTnT` and `TnTOutput` and updated documentation. See the updated https://marlin-na.github.io/TnT/reference/TnT-shiny.html , and please reinstall with `devtools::install_github("marlin-na/TnT")`.

I removed the `renderTnT` and `TnTOutput` for a while during development (since they do not work with S4 class) and what you found is a orphaned documentation page. I did some workaround so that they are working now. I have also removed other orphaned pages in the documentation site.

Sorry for the inconvenience.

**Comment by UmaSangumathi** [comment]
Awesome, it works. Thanks for quick reply :+1:
